// Generated by dojo-bindgen on Mon, 25 Mar 2024 19:30:30 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `zknight::models::character::Character` model
public class Character : ModelInstance {
    [ModelField("game_id")]
    public uint game_id;

    [ModelField("_type")]
    public byte _type;

    [ModelField("health")]
    public byte health;

    [ModelField("index")]
    public uint index;

    [ModelField("hitter")]
    public byte hitter;

    [ModelField("hit")]
    public byte hit;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        