// Generated by dojo-bindgen on Mon, 25 Mar 2024 19:30:30 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `zknight::models::game::Game` model
public class Game : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("game_id")]
    public uint game_id;

    [ModelField("over")]
    public bool over;

    [ModelField("seed")]
    public FieldElement seed;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        