// Generated by dojo-bindgen on Mon, 25 Mar 2024 19:30:30 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `zknight::models::map::Map` model
public class Map : ModelInstance {
    [ModelField("game_id")]
    public uint game_id;

    [ModelField("level")]
    public uint level;

    [ModelField("size")]
    public uint size;

    [ModelField("spawn")]
    public bool spawn;

    [ModelField("score")]
    public byte score;

    [ModelField("over")]
    public bool over;

    [ModelField("name")]
    public FieldElement name;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        