// Generated by dojo-bindgen on Mon, 25 Mar 2024 19:30:30 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `zknight::models::tile::Tile` model
public class Tile : ModelInstance {
    [ModelField("game_id")]
    public uint game_id;

    [ModelField("level")]
    public uint level;

    [ModelField("index")]
    public uint index;

    [ModelField("_type")]
    public byte _type;

    [ModelField("x")]
    public uint x;

    [ModelField("y")]
    public uint y;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        